SELECT TOP 1000 [RoomId]
			  ,[RoomNumber]
			  ,[RoomImage]
			  ,[RoomPrice]
			  ,[RoomTypeID]
			  ,[BookStatusId]
			  ,[RoomCapacity]
			  ,[RoomDescription]
			  ,[IsActive]
FROM [HotelDB].[Hotel].[Rooms]