SELECT TOP 1000 [RoomId]
			  ,[RoomNumber]
			  ,[RoomImage]
			  ,[RoomPrice]
			  ,[BookingStatusId]
			  ,[RoomTypeId]
			  ,[RoomCapacity]
			  ,[RoomDescription]	
			  ,[IsActive]
FROM [HotelDB].[Hotel].[Rooms]